checks_SOURCES		= checks.c check_classify.c check_compare.c check_memory.c
checks_CFLAGS		= $(DONNA_CFLAGS) $(LIBCORE_CFLAGS) $(OPENSSL_CFLAGS)
checks_LDADD		= $(DONNA_LIBS) $(LIBCORE_LIBS) $(OPENSSL_LIBS)

include ../../check.mk
