checks_SOURCES		= checks.c check_classify.c check_compare.c check_memory.c check_host_folder.c check_hash.c check_mail_counters.c check_mail_mime.c
checks_CFLAGS		= $(DONNA_CFLAGS) $(LIBCORE_CFLAGS) $(OPENSSL_CFLAGS)
checks_LDADD		= $(DONNA_LIBS) $(LIBCORE_LIBS) $(OPENSSL_LIBS)

include ../../check.mk
