#ifndef MAGMA_CORE_MIME_H 
#define MAGMA_CORE_MIME_H

// Email message types.
#define MESSAGE_TYPE_UNKNOWN 0
#define MESSAGE_TYPE_PLAIN 1
#define MESSAGE_TYPE_HTML 2
#define MESSAGE_TYPE_MULTI_ALTERNATIVE 3
#define MESSAGE_TYPE_MULTI_MIXED 4
#define MESSAGE_TYPE_MULTI_RELATED 5
#define MESSAGE_TYPE_MULTI_RFC822 5
#define MESSAGE_TYPE_MULTI_UNKOWN 6

// Email message encodings.
#define MESSAGE_ENCODING_UNKNOWN 0
#define MESSAGE_ENCODING_QUOTED_PRINTABLE 1
#define MESSAGE_ENCODING_BASE64 2
#define MESSAGE_ENCODING_7BIT 3
#define MESSAGE_ENCODING_8BIT 4


#endif
