
# Library Name
ARCHIVE			:= libdmessage.a


# Source files
SRCFILES := parser.c chunk.c dmsg.c


# The list of include paths
INCLUDES		:= -I../../include/ -I../../include/common/ -I../../deps/sources/donna -I../../deps/sources/openssl/include

include ../../library.mk
