
# Module name
ARCHIVE			:= libcommon.a


# Source files
SRCFILES := crypto_pub.c crypto.c error.c misc_pub.c misc.c network_pub.c network.c


# The list of include paths
INCLUDES		:= -I../../include/ -I../../include/common/ -I../../deps/sources/donna -I../../deps/sources/openssl/include

include ../../library.mk
