ARCHIVE			:= libcommon.a

SRCFILES := crypto_pub.c crypto.c error.c misc_pub.c misc.c network_pub.c network.c

INCLUDES		:= -I../../include/ -I../../deps/sources/donna -I../../deps/sources/openssl/include

CFLAGS.misc.c = -Wno-format-nonliteral

include ../../library.mk
