
# Library Name
ARCHIVE			:= libsignet-resolver.a


# Source Files
SRCFILES := cache_pub.c cache.c dmtp_pub.c dmtp.c dns_pub.c dns.c mrec_pub.c mrec.c ssl_pub.c ssl.c


# The list of include paths
INCLUDES		:= -I../../include/ -I../../include/common/ -I../../deps/sources/donna -I../../deps/sources/openssl/include

include ../../library.mk
