ARCHIVE			:= libsignet-resolver.a

SRCFILES := cache_pub.c cache.c dmtp_pub.c dmtp.c dns_pub.c dns.c mrec_pub.c mrec.c ssl_pub.c ssl.c

INCLUDES		:= -I../../include/ -I../../deps/sources/donna -I../../deps/sources/openssl/include

include ../../library.mk
