df = $(DEPDIRNAME)/$(*F)

$(OBJDIRNAME) $(DEPDIRNAME):
	test -d $@ || mkdir $@

$(OBJDIRNAME)/%.o : %.c | $(OBJDIRNAME) $(DEPDIRNAME)
	@echo Compiling..
	$(CC) -M -MF $(df).d.tmp $(CFLAGS) $(ALL_INC_CCOPT) -fPIC -c $<
	@sed -e 's,^\($*\)\.o,$(OBJDIRNAME)/\1.o,' < $(df).d.tmp > $(df).d; \
	sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e 's/$$/ :/' -e 's/^ *//' < $(df).d.tmp >> $(df).d ; \
		rm -f $(df).d.tmp
	$(CC) $(CFLAGS) $(ALL_INC_CCOPT) -fPIC -c $< -o $@

-include $(DEPFILES)
