
# Library Name
ARCHIVE			:= libsignet.a


# Source files
SRCFILES := general.c keys_pub.c keys.c signet_pub.c signet.c


# The list of include paths
INCLUDES		:= -I../../include/ -I../../include/common/ -I../../deps/sources/donna -I../../deps/sources/openssl/include

include ../../library.mk
