ARCHIVE			:= libsignet.a

SRCFILES := general.c keys_pub.c keys.c signet_pub.c signet.c

INCLUDES		:= -I../../include/ -I../../deps/sources/donna -I../../deps/sources/openssl/include

include ../../library.mk
