
# Module name
ARCHIVE			:= libcore.a


# Source files
SRCFILES := buckets/arrays.c buckets/pool.c buckets/stacked.c classify/ascii.c compare/search.c compare/equal.c \
compare/ends.c compare/starts.c encodings/base64.c encodings/hex.c encodings/qp.c encodings/url.c encodings/mappings.c \
encodings/zbase32.c hash/adler.c hash/fletcher.c hash/crc.c hash/murmur.c host/files.c host/host.c host/spool.c \
host/folder.c host/mappings.c host/process.c indexes/inx.c indexes/hashed.c indexes/cursors.c indexes/linked.c \
log/log.c mail/counters.c mail/mime.c mail/headers.c memory/align.c memory/bits.c memory/memory.c memory/secure.c \
parsers/trim.c parsers/line.c parsers/time.c parsers/numbers/numbers.c parsers/numbers/digits.c parsers/case.c \
parsers/formats/nvp.c parsers/token.c parsers/special/bracket.c strings/opts.c strings/info.c strings/length.c \
strings/allocation.c strings/replace.c strings/data.c strings/print.c strings/multi.c strings/validate.c \
strings/shortcuts.c strings/nuller.c thread/rwlock.c thread/keys.c thread/thread.c thread/mutex.c global.c other.c \
type.c


# The list of include paths
INCLUDES		:= -I../../include/ -I../../include/core/ -I../../include/common/ -I../../deps/sources/donna -I../../deps/sources/openssl/include

include ../../library.mk
